# Generated by Django 3.0.1 on 2019-12-30 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='albums/gallery/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Album')),
            ],
        ),
        migrations.DeleteModel(
            name='AlbumImage',
        ),
    ]
