# Generated by Django 3.0.1 on 2019-12-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_auto_20191230_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='albumimages',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
