# Generated by Django 3.0.1 on 2019-12-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20191230_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
