# Generated by Django 3.0.1 on 2019-12-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20191230_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(unique=100),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('title', 'slug')},
        ),
    ]
