# Generated by Django 3.0.1 on 2020-01-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_auto_20191230_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimages',
            name='image',
            field=models.ImageField(upload_to='albums/images'),
        ),
    ]
